
GET http://localhost:3000/players/



###

DELETE http://localhost:3000/players/6/

###


GET http://localhost:3000/players/1

###
POST http://localhost:3000/players
Content-Type: application/json

{
  "playerName": "Vishal",
  "jerseyNumber": 17,
  "role": "Bowler"
}

###

PUT  http://localhost:3000/players/6
Content-Type: application/json

{
  "playerName": "Maneesh",
  "jerseyNumber": 54,
  "role": "All-rounder"
}

###
GET http://localhost:3000/players/ 
### 

POST http://localhost:3000/players/